name: 'Setup .NET Tests'
description: 'Setup .NET SDK, restore, build, and install Playwright for system tests'

runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: optivem/actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore System Test Dependencies
      run: dotnet restore
      working-directory: dotnet
      shell: bash

    - name: Compile System Tests
      run: dotnet build --no-restore --configuration Release
      working-directory: dotnet
      shell: bash

    - name: Install Playwright browsers
      run: |
        dotnet build
        pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      working-directory: dotnet/SystemTests
      shell: bash
