name: java-acceptance-stage

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:

jobs:

  system-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy Acceptance Environment
        uses: ./.github/actions/deploy-acceptance-environment

      - name: Setup Java Tests
        uses: ./.github/actions/setup-java-tests

      - name: Smoke (Stub)
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=smoke -DexternalSystemMode=stub -Denvironment=acceptance
        working-directory: java

      - name: Smoke (Real)
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=smoke -DexternalSystemMode=real -Denvironment=acceptance
        working-directory: java

      - name: Acceptance - API Channel
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=acceptance -DexcludeTags=isolated -Dchannel=API -Denvironment=acceptance
        working-directory: java

      - name: Acceptance - UI Channel
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=acceptance -DexcludeTags=isolated -Dchannel=UI -Denvironment=acceptance
        working-directory: java

      - name: Acceptance (Isolated) - API Channel
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=acceptance -DincludeTags=isolated -Dchannel=API -Denvironment=acceptance
        working-directory: java

      - name: Acceptance (Isolated) - UI Channel
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=acceptance -DincludeTags=isolated -Dchannel=UI -Denvironment=acceptance
        working-directory: java

      - name: Contract (Stub)
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=contract -DexternalSystemMode=stub -Denvironment=acceptance
        working-directory: java

      - name: Contract (Real)
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=contract -DexternalSystemMode=real -Denvironment=acceptance
        working-directory: java

      - name: E2E - API Channel
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=e2e -Dchannel=API -Denvironment=acceptance
        working-directory: java

      - name: E2E - UI Channel
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=e2e -Dchannel=UI -Denvironment=acceptance
        working-directory: java
