name: java-acceptance-stage

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:

jobs:

  system-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy System (Real External Systems)
        uses: ./.github/actions/deploy-docker-images
        with:
          environment: acceptance
          version: latest
          external-system-mode: 'real'
          frontend-url: 'http://localhost:3001/'
          backend-url: 'http://localhost:8081/health'
          erp-url: 'http://localhost:9001/erp/health'
          tax-url: 'http://localhost:9001/tax/health'

      - name: Deploy System (Stub External Systems)
        uses: ./.github/actions/deploy-docker-images
        with:
          environment: acceptance
          version: latest
          external-system-mode: 'stub'
          frontend-url: 'http://localhost:3002/'
          backend-url: 'http://localhost:8082/health'
          erp-url: 'http://localhost:9002/erp/health'
          tax-url: 'http://localhost:9002/tax/health'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install Playwright Dependencies
        run: npx playwright install --with-deps chromium
        working-directory: java

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew
        working-directory: java

      - name: Build Project
        run: ./gradlew clean compileJava compileTestJava
        working-directory: java

      - name: Smoke (Stub)
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=smoke -DexternalSystemMode=stub -Denvironment=acceptance
        working-directory: java

      - name: Smoke (Real)
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=smoke -DexternalSystemMode=real -Denvironment=acceptance
        working-directory: java

      - name: Acceptance - API Channel
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=acceptance -DexcludeTags=isolated -Dchannel=API -Denvironment=acceptance
        working-directory: java

      - name: Acceptance - UI Channel
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=acceptance -DexcludeTags=isolated -Dchannel=UI -Denvironment=acceptance
        working-directory: java

      - name: Acceptance (Isolated) - API Channel
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=acceptance -DincludeTags=isolated -Dchannel=API -Denvironment=acceptance
        working-directory: java

      - name: Acceptance (Isolated) - UI Channel
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=acceptance -DincludeTags=isolated -Dchannel=UI -Denvironment=acceptance
        working-directory: java

      - name: Contract (Stub)
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=contract -DexternalSystemMode=stub -Denvironment=acceptance
        working-directory: java

      - name: Contract (Real)
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=contract -DexternalSystemMode=real -Denvironment=acceptance
        working-directory: java

      - name: E2E - API Channel
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=e2e -Dchannel=API -Denvironment=acceptance
        working-directory: java

      - name: E2E - UI Channel
        run: ./gradlew :system-test:test -Dversion=latest -Dtype=e2e -Dchannel=UI -Denvironment=acceptance
        working-directory: java
