name: typescript-acceptance-stage

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:

jobs:

  system-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Deploy Acceptance Environment
        uses: ./.github/actions/deploy-acceptance-environment

      - name: Setup TypeScript Tests
        uses: ./.github/actions/setup-typescript-tests

      - name: Smoke (Stub)
        run: npx playwright test --project=smoke-test tests/latest/smoke
        working-directory: typescript/system-test
        env:
          ENVIRONMENT: acceptance
          EXTERNAL_SYSTEM_MODE: STUB

      - name: Smoke (Real)
        run: npx playwright test --project=smoke-test tests/latest/smoke
        working-directory: typescript/system-test
        env:
          ENVIRONMENT: acceptance
          EXTERNAL_SYSTEM_MODE: REAL

      - name: Acceptance - API Channel
        run: npx playwright test --project=acceptance-test tests/latest/acceptance --grep-invert "@isolated"
        working-directory: typescript/system-test
        env:
          ENVIRONMENT: acceptance
          EXTERNAL_SYSTEM_MODE: STUB
          CHANNEL: API

      - name: Acceptance - UI Channel
        run: npx playwright test --project=acceptance-test tests/latest/acceptance --grep-invert "@isolated"
        working-directory: typescript/system-test
        env:
          ENVIRONMENT: acceptance
          EXTERNAL_SYSTEM_MODE: STUB
          CHANNEL: UI

      - name: Acceptance (Isolated) - API Channel
        run: npx playwright test --project=acceptance-test tests/latest/acceptance --grep "@isolated" --workers=1
        working-directory: typescript/system-test
        env:
          ENVIRONMENT: acceptance
          EXTERNAL_SYSTEM_MODE: STUB
          CHANNEL: API

      - name: Acceptance (Isolated) - UI Channel
        run: npx playwright test --project=acceptance-test tests/latest/acceptance --grep "@isolated" --workers=1
        working-directory: typescript/system-test
        env:
          ENVIRONMENT: acceptance
          EXTERNAL_SYSTEM_MODE: STUB
          CHANNEL: UI

      - name: Contract (Stub)
        run: npx playwright test --project=external-system-contract-test tests/latest/contract --workers=1
        working-directory: typescript/system-test
        env:
          ENVIRONMENT: acceptance
          EXTERNAL_SYSTEM_MODE: STUB

      - name: Contract (Real)
        run: npx playwright test --project=external-system-contract-test tests/latest/contract --workers=1
        working-directory: typescript/system-test
        env:
          ENVIRONMENT: acceptance
          EXTERNAL_SYSTEM_MODE: REAL

      - name: E2E - API Channel
        run: npx playwright test --project=e2e-test tests/latest/e2e
        working-directory: typescript/system-test
        env:
          ENVIRONMENT: acceptance
          CHANNEL: API

      - name: E2E - UI Channel
        run: npx playwright test --project=e2e-test tests/latest/e2e
        working-directory: typescript/system-test
        env:
          ENVIRONMENT: acceptance
          CHANNEL: UI
